server:
  port: 9001
spring:
  application:
    name: stock-service
#  profiles:
#    active: ft1
  redis:
    url: localhost
    password: root123
    database: 0
    port: 6379
  datasource:
    hikari:
      connection-test-query: select 1
      maximum-pool-size: 100
      max-lifetime: 30000
      minimum-idle: 10
    url: jdbc:log4jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: root123
    driver-class-name: net.sf.log4jdbc.DriverSpy
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: fuhx
    username: admin
    password: admin123
    #消息确认模式（NONE不确认，AUTO自动确认，MANUAL手动确认）
    listener:
      simple:
        acknowledge-mode: manual

dubbo:
  application:
    name: stock-service
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    name: dubbo
    prot: -1
  consumer:
    timeout: 100000
logging:
  config: classpath:log4j2.xml
#暴露端点，这样actuator就可以监控的到健康状况
management:
  endpoints:
    web:
      exposure:
        include: '*'

mybatis:
  mapper-locations:
    - classpath*:/mapper/*Dao.xml
  type-aliases-package: com.fuhx.entity

seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: my_test_tx_group
  enable-auto-data-source-proxy: true
  config:
    type: nacos
    nacos:
      namespace: "6744230a-8663-471a-88b0-3c277610b521"
      serverAddr: 127.0.0.1:8848
      group: "DEFAULT_GROUP"
      data-id: "seataServer.properties"
      userName: ""
      password: ""
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      namespace: "6744230a-8663-471a-88b0-3c277610b521"
      userName: ""
      password: ""
      group: "DEFAULT_GROUP"
