server:
  port: 8888
spring:
  application:
    name: gateway
#  profiles:
#    active: dev
  redis:
    url: 127.0.0.1
    password: root123
    database: 0
    port: 6379
  datasource:
    hikari:
      connection-test-query: select 1
      maximum-pool-size: 100
      max-lifetime: 30000
      minimum-idle: 10
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/seata?useUnicode=true&characterEncoding=utf8
    username: root
    password: root123
    driver-class-name: net.sf.log4jdbc.DriverSpy
logging:
  config: classpath:log4j2.xml
#暴露端点，这样actuator就可以监控的到健康状况
management:
  endpoints:
    web:
      exposure:
        include: '*'
dubbo:
  application:
    name: gateway
  registry:
    address: nacos://127.0.0.1:8848
    port: -1
  protocol:
    name: dubbo
  consumer:
    timeout: 100000
mybatis:
  mapper-locations:
    - classpath*:/mapper/*Dao.xml
  type-aliases-package: com.fhx.entity