server:
  port: 9002
spring:
  application:
    name: order-service
  redis:
    url: localhost
    password: root123
    database: 0
    port: 6379
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: root123
    driver-class-name: net.sf.log4jdbc.DriverSpy
    hikari:
      connection-test-query: select 1
      maximum-pool-size: 100
      max-lifetime: 30000
      minimum-idle: 10
logging:
  config: classpath:log4j2.xml
  #暴露端点，这样actuator就可以监控的到健康状况
  management:
    endpoints:
      web:
        exposure:
          include: '*'
#debug: true
mybatis:
  mapper-locations:
    - classpath*:/mapper/*-Mapper.xml
  type-aliases-package: com.fhx.entity
dubbo:
  application:
    name: order
  registry:
    address: nacos://101.133.234.7:8848
  protocol:
    name: dubbo
  consumer:
    timeout: 100000